# Generated by Django 4.2.2 on 2023-06-15 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('preface', models.CharField(blank=True, max_length=150, null=True)),
                ('category', models.CharField(choices=[('Tech', 'Tech'), ('Fashion', 'Fashion'), ('Entertainment', 'Entertainment'), ('Politics', 'Politics')], default='Tech', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/2023-06-15')),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Publish', 'Publish')], default='Publish', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
